name: New Event
description: Register a Claude Code community event
title: "[Event] YYYY-MM-DD City Name"
labels: ["event"]
body:
  - type: input
    id: event-name
    attributes:
      label: Event Name
      placeholder: "Claude Code Meetup Miami"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Date
      placeholder: "YYYY-MM-DD"
    validations:
      required: true

  - type: input
    id: city
    attributes:
      label: City
      placeholder: "Miami"
    validations:
      required: true

  - type: input
    id: luma-url
    attributes:
      label: Luma Event URL
      placeholder: "https://lu.ma/your-event"
    validations:
      required: true

  - type: input
    id: speakers
    attributes:
      label: Number of Speakers
      placeholder: "5"

  - type: textarea
    id: notes
    attributes:
      label: Notes
      placeholder: "Any additional context."
